services:
  - name: realworld-backend
    type: web
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    buildCommand: npm run build
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realworld-db
          property: connectionString

databases:
  - name: realworld-db
    region: oregon
    databaseName: realworld
    user: realworld_user
    plan: standard
